# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Run all tasks in the project
    cmds:
      - task: asellidae
      - task: copepoda

includes:
  asellidae:
    taskfile: ./datasets/Asellidae/Taskfile.yml
    dir: ./datasets/Asellidae
  copepoda:
    taskfile: ./datasets/Copepoda/Taskfile.yml
    dir: ./datasets/Copepoda
