# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Run all tasks in the project
    cmds:
      - task: asellidae
      - task: copepoda
      - task: ostracoda
      - task: austria
      - task: spiders
      - mkdir -p res
      - cp datasets/Asellidae/res/Aselloidea_occurrences.json -t res/
      - cp datasets/Copepoda/res/Copepoda_occurrences.json -t res/
      - cp datasets/Ostracoda/res/Ostracoda.json -t res/
      - cp datasets/Austria/res/Asellidae_Austria.json -t res/
      - cp datasets/Spiders/res/Spiders.json -t res/

includes:
  asellidae:
    taskfile: ./datasets/Asellidae/Taskfile.yml
    dir: ./datasets/Asellidae
  copepoda:
    taskfile: ./datasets/Copepoda/Taskfile.yml
    dir: ./datasets/Copepoda
  ostracoda:
    taskfile: ./datasets/Ostracoda/Taskfile.yml
    dir: ./datasets/Ostracoda
  spiders:
    taskfile: ./datasets/Spiders/Taskfile.yml
    dir: ./datasets/Spiders
  austria:
    taskfile: ./datasets/Austria/Taskfile.yml
    dir: ./datasets/Austria
