# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Run all tasks in the project
    cmds:
      - task: asellidae
      - task: copepoda

includes:
  asellidae:
    taskfile: ./Asellidae/Taskfile.yml
    dir: ./Asellidae
  copepoda:
    taskfile: ./Copepoda/Taskfile.yml
    dir: ./Copepoda
