# https://taskfile.dev

version: "3"

vars:
  INPUT_DATA: data/Dataset.tsv
  TAXONOMY_FIX: data/taxonomy_fix.tsv
  AFF_CF_FIX: data/aff_cf.tsv
  HABITATS: data/habitats.tsv
  GBIF: data/GBIF_censor_recovery.tsv
  MISSING_COORDS: data/coordinates_recovery.tsv
  MISSING_TAXA_FILE: data/missing_taxa.txt
  # PREPROCESSED_FILE: res/Ostracoda.tsv
  OUTPUT_FILE: res/Ostracoda.tsv
  METADATA_JSON: data/metadata.json
  METADATA_TAXONOMY: res/unclassified_taxa.json
  METADATA_UNREFERENCED_TAXA: res/unreferenced_taxa.json

tasks:
  # default:
  #   cmds:
  #     - uv run scripts/ostracoda.py {{.PREPROCESSED_FILE}} {{.OUTPUT_FILE}} --metadata={{.METADATA_JSON}} --taxonomy={{.METADATA_TAXONOMY}} --unreferenced_taxa={{.METADATA_UNREFERENCED_TAXA}}
  #   desc: Generate Ostracoda occurrences dataset in ready to import JSON format
  #   sources:
  #     - scripts/*.py
  #     - "{{.PREPROCESSED_FILE}}"
  #     - "{{.METADATA_TAXONOMY}}"
  #     - "{{.METADATA_JSON}}"
  #     - "{{.METADATA_UNREFERENCED_TAXA}}"

  #   generates:
  #     - "{{.OUTPUT_FILE}}"
  #   deps:
  #     - preprocess
  #     - taxonomy
  #     - unreferenced_taxa

  # taxonomy:
  #   cmds:
  #     - Rscript scripts/unclassified_taxa.R {{.PREPROCESSED_FILE}} {{.METADATA_TAXONOMY}}
  #   desc: Generate Ostracoda taxonomy file
  #   sources:
  #     - scripts/unclassified_taxa.R
  #     - "{{.PREPROCESSED_FILE}}"
  #   generates:
  #     - res/unclassified_taxa.json
  #   deps:
  #     - preprocess

  # unreferenced_taxa:
  #   cmds:
  #     - Rscript scripts/unreferenced_taxa.R --preprocessed={{.PREPROCESSED_FILE}} {{.MISSING_TAXA_FILE}} {{.METADATA_UNREFERENCED_TAXA}}
  #   desc: Generate Ostracoda unreferenced taxa file
  #   sources:
  #     - scripts/unreferenced_taxa.R
  #     - "{{.MISSING_TAXA_FILE}}"
  #     - "{{.PREPROCESSED_FILE}}"
  #   generates:
  #     - res/unreferenced_taxa.json
  #   deps:
  #     - preprocess

  default:
    cmds:
      - Rscript scripts/ostracoda.R {{.INPUT_DATA}} {{.OUTPUT_FILE}} --taxonomy-fix {{.TAXONOMY_FIX}} --aff-cf-fix {{.AFF_CF_FIX}} --habitats {{.HABITATS}} --gbif {{.GBIF}} --missing-coords {{.MISSING_COORDS}}
    desc: Preprocess Ostracoda dataset
    sources:
      - scripts/ostracoda.R
      - "{{.INPUT_DATA}}"
    generates:
      - "{{.OUTPUT_FILE}}"
    deps:
      - make_res_dir

  make_res_dir:
    cmds:
      - mkdir -p res
    desc: Create the res directory if it doesn't exist
    generates:
      - res
    silent: true

  clean:
    cmds:
      - rm -rf res
    desc: Clean the res directory
    silent: true
